# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_V3_1 <- function(X, G, Y, mu) {
    .Call('_MATGEI_get_V3_1', PACKAGE = 'MATGEI', X, G, Y, mu)
}

